- name: Install libmilter-dev
  apt:
    name: libmilter-dev
    state: present

- name: Install dkimpy-milter
  pip:
    name: "{{ packages }}"
  vars:
    packages:
      - pymilter
      - dkimpy-milter

- name: Ensure group "{{ dkimpy_group }}" exists
  group:
    name: "{{ dkimpy_group }}"
    system: yes
    state: present

- name: Ensure user "{{ dkimpy_user }}" exists
  user:
    name: "{{ dkimpy_user }}"
    group: "{{ dkimpy_group }}"
    comment: DKIM Python Milter
    system: yes
    shell: /bin/false
    home: "/run/{{ dkimpy_user }}"
    create_home: no

# Put the config file where dkimpy-milter's systemd unit file expects it
- name: Install dkimpy-milter config file
  template:
    src: dkimpy-milter.conf
    dest: /usr/local/etc/dkimpy-milter/dkimpy-milter.conf
    owner: "{{ dkimpy_user }}"
    group: "{{ dkimpy_group }}"
    mode: "0640"
  notify: restart dkimpy-milter

- name: Create "{{ dkimpy_key_store }}"
  file:
    path: "{{ dkimpy_key_store }}"
    state: directory
    owner: "{{ dkimpy_user }}"
    group: "{{ dkimpy_group }}"
    mode: "0750"

# Create any rsa key specified – enabled or disabled
- name: Create rsa type DKIM keys
  command:
    cmd: "dknewkey --ktype rsa {{ dkimpy_key_store }}/{{ rsa_key_file_name }}"
    creates: "{{ dkimpy_key_store }}/{{ rsa_key_file_name }}.key"
  become: yes
  become_user: "{{ dkimpy_user }}"
  no_log: true
  loop: "{{ lookup('dict', rsa_keys) }}"

# Create any ed25519 key specified – enabled or disabled
- name: Create ed25519 type DKIM keys
  command:
    cmd: "dknewkey --ktype ed25519 {{ dkimpy_key_store }}/{{ ed25519_key_file_name }}"
    creates: "{{ dkimpy_key_store }}/{{ ed25519_key_file_name }}.key"
  become: yes
  become_user: "{{ dkimpy_user }}"
  no_log: true
  loop: "{{ lookup('dict', ed25519_keys) }}"

- name: Deploy rsa KeyTable
  template:
    src: KeyTable
    dest: "{{ dkimpy_key_table }}"
    owner: "{{ dkimpy_user }}"
    group: "{{ dkimpy_group }}"
    mode: "0640"
  notify: restart dkimpy-milter

- name: Deploy ed25519 KeyTable
  template:
    src: KeyTableEd25519
    dest: "{{ dkimpy_key_ed25519_table }}"
    owner: "{{ dkimpy_user }}"
    group: "{{ dkimpy_group }}"
    mode: "0640"
  notify: restart dkimpy-milter

- name: Deploy SigningTable
  template:
    src: SigningTable
    dest: "{{ dkimpy_signing_table }}"
    owner: "{{ dkimpy_user }}"
    group: "{{ dkimpy_group }}"
    mode: "0640"
  notify: restart dkimpy-milter

- name: Create "{{ dkimpy_postfix_socket_directory }}"
  file:
    path: "{{ dkimpy_postfix_socket_directory }}"
    state: directory
    owner: "{{ dkimpy_user }}"
    group: "{{ postfix_group }}"
    mode: "0710"
  when: dkimpy_socket == "local_postfix"
  notify: restart dkimpy-milter

- name: Enable dkimpy-milter service
  systemd:
    name: dkimpy-milter
    daemon_reload: yes
    enabled: yes
    state: started

